-- USING DATABASE PRO
use pro;
----------------------------------------------------------------------------------------------------------
-- CHECKING ALL THE DATA TABLES
SELECT * FROM LOAN
SELECT * FROM CUSTOMER;
SELECT * FROM LOAN_COUNT_BY_YEAR
SELECT * FROM LOAN_PURPOSES
SELECT * FROM LOAN_WITH_REGION
SELECT * FROM STATE_REGION
----------------------------------------------------------------------------------------------------
-- CREATING THE FINAL TABLE FOR ANALYSIS
CREATE TABLE FINAL_DATA
SELECT 
L.LOAN_ID,
L.LOAN_STATUS,
L.LOAN_AMOUNT,
L.TERM,
L.INT_RATE,
L.INSTALLMENT,
L.GRADE,
L.PURPOSE,
C.HOME_OWNERSHIP,
C.ANNUAL_INC,
C.AVG_CUR_BAL,
C.TOT_CUR_BAL,
LY.ISSUE_YEAR,
LSR.STATE,
LSR.SUBREGION
FROM LOAN AS L
LEFT JOIN CUSTOMER AS C  ON L.CUSTOMER_ID = C.CUSTOMER_ID
LEFT JOIN  LOAN_COUNT_BY_YEAR AS LY  ON L.ISSUE_YEAR = LY.ISSUE_YEAR
LEFT JOIN LOAN_WITH_REGION   AS LR ON L.LOAN_ID = LR.LOAN_ID
LEFT JOIN STATE_REGION AS LSR ON L.STATE = LSR.STATE
-------------------------------------------------------------------------------------------------
-- FORMATTING COLUMN NAMES
ALTER TABLE FINAL_DATA
RENAME COLUMN INT_RATE TO INTREST;

ALTER TABLE FINAL_DATA
RENAME COLUMN ANNUAL_INC TO ANNUAL_INCOME

ALTER TABLE FINAL_DATA
RENAME COLUMN AVG_CUR_BAL TO AVERAGE_CURRENT_BALANCE;

ALTER TABLE FINAL_DATA
RENAME COLUMN TOT_CUR_BAL TO TOTAL_CURRENT_BALANCE;

ALTER TABLE FINAL_DATA
RENAME COLUMN TERM TO LOAN_TERM;

--------------------------------------------------------------------------------------------------
-- BASIC DATA CLEANING AND FORMATING
UPDATE FINAL_DATA
SET INSTALLMENT =  ROUND(INSTALLMENT,2);

UPDATE FINAL_DATA 
SET PURPOSE = CONCAT(UPPER(LEFT(PURPOSE,1)),LOWER(SUBSTRING(PURPOSE,2)));

UPDATE FINAL_DATA 
SET HOME_OWNERSHIP = CONCAT(UPPER(LEFT(HOME_OWNERSHIP,1)),LOWER(SUBSTRING(HOME_OWNERSHIP,2)));

UPDATE FINAL_DATA
SET INTREST = ROUND(INTREST * 100);

UPDATE FINAL_DATA
SET INTREST = INTREST/10000;
--------------------------------------------------------------------------------------------------------
-- CHECKING FINAL DATASET 
SELECT * FROM FINAL_DATA;


